apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fcsapp.fullname" . }}-migration
  labels:
    {{- include "fcsapp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./fcstask-migrate"]
          volumeMounts:
            - name: app-config
              mountPath: /home/fcstask-admin/config/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: app-config
          secret:
            secretName: {{ include "fcsapp.fullname" . }}-config