groups:
  - name: fcstask-alerts
    rules:
      - alert: HighHTTP500Errors
        expr: { { .DEBUG_RULE } }
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "HTTP 500 errors detected on {{ $labels.instance }}"
          description: "Service {{ $labels.instance }} has returned HTTP 500 errors. Current value: {{ $value }}"
